### PR TITLE
Fix dereference of invalid iterator after erasing.

### LINKED ISSUE #1: cppcheck error: iterator 'bi' used after element has been erased
From richelbilderbeek
https://bitbucket.org/giszmo/glob2/issues/8/cppcheck-error-iterator-bi-used-after

When running cppcheck (see [Travis build log](https://travis-ci.org/richelbilderbeek/globulation2/builds/564008690)), it detects the following errors:

```
[Building.cpp:2783]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
[Building.cpp:2788]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
[Building.cpp:2821]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
[Building.cpp:2830]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
[Building.cpp:2840]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
[Building.cpp:2860]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
[Building.cpp:2878]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
[Game.cpp:1560] -> [Game.cpp:1559]: (error) Iterator 'bi' used after element has been erased.
```

Focusing on the last error:
`
[Game.cpp:1560] -> [Game.cpp:1559]: (error) Iterator 'bi' used after element has been erased.
`

These are the lines it is about:
```
for (std::list<Building *>::iterator bi=teams[ti]->virtualBuildings.begin(); bi!=teams[ti]->virtualBuildings.end(); ++bi)
    if ((*bi)->posX==x && (*bi)->posY==y)
    {
        teams[ti]->virtualBuildings.erase(bi);                      //1559
        teams[ti]->myBuildings[Building::GIDtoID((*bi)->gid)]=NULL; //1560
        delete *bi;
        found=true;
        break;
    }
```

Changing the order to this fixes the cppcheck error:
```
for (std::list<Building *>::iterator bi=teams[ti]->virtualBuildings.begin(); bi!=teams[ti]->virtualBuildings.end(); ++bi)
    if ((*bi)->posX==x && (*bi)->posY==y)
    {
        teams[ti]->myBuildings[Building::GIDtoID((*bi)->gid)]=NULL;
        delete *bi;
        teams[ti]->virtualBuildings.erase(bi);
        found=true;
        break;
    }
```
If this proposal is accepted, I volunteer to submit a Pull Request with the fix 👍

### PR DESCRIPTION
**Pull request by Quipyowert2**
Fixes #1.

### CODE REVIEW

File: src/Game.cpp [hunk 1]
```diff
@@ -1553,9 +1553,9 @@ bool Game::removeUnitAndBuildingAndFlags(int x, int y, unsigned flags)
 			for (std::list<Building *>::iterator bi=teams[ti]->virtualBuildings.begin(); bi!=teams[ti]->virtualBuildings.end(); ++bi)
 				if ((*bi)->posX==x && (*bi)->posY==y)
 				{
-					teams[ti]->virtualBuildings.erase(bi);
 					teams[ti]->myBuildings[Building::GIDtoID((*bi)->gid)]=NULL;
 					delete *bi;
+					bi = teams[ti]->virtualBuildings.erase(bi);
```
Comment (stephanemagnenat) [inline src/Game.cpp:1558]: Why do we reassign `bi` here? We are breaking out of the loop in which `bi` is a local variable just after that.

Comment (Quipyowert2) [reply src/Game.cpp]: Oops. I guess I wasn't paying attention when I made the patch. I've force-pushed a new commit with the erase but without assigning to `bi`.
